# This is a workflow to publish the react application to the kubernetes.

name: Publish-React-App

# Controls when the workflow will run
on:
  push:
    branches: 
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  react-build:
    runs-on: node-latest
    steps:
    - name: npm install
      run: npm install
    - name: npm run build
      run: npm run build