# This is a workflow to publish the react application to the kubernetes.

name: Publish-React-App

# Controls when the workflow will run
on:
  push:
    branches: 
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  VERSION_NUMBER: $GITHUB_SHA-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER
  PROJECT_URL: $GITHUB_REPOSITORY
  AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}

jobs:
  react-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build
  
  docker-build:
    runs-on: ubuntu-latest
    needs: react-build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t $AWS_ECR_URL/$PROJECT_URL:$VERSION_NUMBER .
          docker push $AWS_ECR_URL/$PROJECT_URL:$VERSION_NUMBER