# This is a workflow to publish the react application to the kubernetes.

name: Publish-React-App

# Controls when the workflow will run
on:
  push:
    branches: 
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  react-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      run: actions/checkout@v2
    - name: Install NodeJS
      run: |
        sudo apt-get update
        sudo apt-get install nodejs